# Generated by Django 2.1.7 on 2019-03-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Makaleye Foto Ekle'),
        ),
    ]
